<?php
namespace Modules\Job\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Models\Categories;
use Modules\Location\Models\Location;
use Modules\Job\Models\Job;
use Modules\Job\Models\JobTerm;
use Modules\Job\Models\JobTranslation;
class JobController extends AdminController
{
    protected $JobClass;
    protected $JobTranslationClass;
    protected $JobTermClass;
    protected $categoriesClass;
    protected $locationClass;

    public function __construct()
    {
        parent::__construct();
        $this->setActiveMenu('admin/module/job');
        $this->JobClass = Job::class;
        $this->JobTranslationClass = JobTranslation::class;
        $this->JobTermClass = JobTerm::class;
        $this->categoriesClass = Categories::class;
        $this->locationClass = Location::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Job::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('job_view');
        $query = $this->JobClass::query() ;
        $query->orderBy('id', 'desc');
        if (!empty($job_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $job_name . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('job_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'job_manage_others' => $this->hasPermission('job_manage_others'),
            'breadcrumbs'        => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/Job'
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Job Management")
        ];
        return view('Job::admin.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('job_create');
        $row = new $this->JobClass();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'            => $row,
            'categories'     => $this->categoriesClass::where('service', 'Job')->get(),
            'job_location' => $this->locationClass::where('status', 'publish')->get()->toTree(),
            'translation'    => new $this->JobTranslationClass(),
            'breadcrumbs'    => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/job'
                ],
                [
                    'name'  => __('Add Job'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Add new Job")
        ];
        return view('Job::admin.detail', $data);
    }
    
    public function recovery(Request $request)
    {
        $this->checkPermission('job_view');
        $query = $this->JobClass::onlyTrashed() ;
        $query->orderBy('id', 'desc');
        if (!empty($job_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $job_name . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('job_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('create_user', $author);
            }
        } else {
            $query->where('create_user', Auth::id());
        }
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'job_manage_others' => $this->hasPermission('job_manage_others'),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/Job'
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Recovery Job Management")
        ];
        return view('Job::admin.index', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('job_update');
        $row = $this->JobClass::find($id);
        if (empty($row)) {
            return redirect(route('job.admin.index'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        if (!$this->hasPermission('job_manage_others')) {
            if ($row->create_user != Auth::id()) {
                return redirect(route('job.admin.index'));
            }
        }
        $data = [
            'row'            => $row,
            'translation'    => $translation,
            "selected_terms" => $row->terms->pluck('term_id'),
            'categories'     => $this->categoriesClass::where('service', 'Job')->get(),
            'job_location'  => $this->locationClass::where('status', 'publish')->get()->toTree(),
            'enable_multi_lang'=>true,
            'breadcrumbs'    => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/job'
                ],
                [
                    'name'  => __('Edit Job'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Edit: :name",['name'=>$row->title])
        ];
        return view('Job::admin.detail', $data);
    }

    public function store( Request $request, $id ){
        if($id>0){
            $this->checkPermission('job_update');
            $row = $this->JobClass::find($id);
            if (empty($row)) {
                return redirect(route('job.admin.index'));
            }
            if($row->create_user != Auth::id() and !$this->hasPermission('job_manage_others'))
            {
                return redirect(route('job.admin.index'));
            }
        }else{
            $this->checkPermission('job_create');
            $row = new $this->JobClass();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'location_id',
            'category_id',
            'address',
            'contact_email',
            'contact_phone',
            'start_at',
            'duration',
            'status',
            'job_type',
        ];
        if($this->hasPermission('job_manage_others')){
            $dataKeys[] = 'create_user';
        }
        $row->fillByAttr($dataKeys,$request->input());
        if($request->input('slug')){
            $row->slug = $request->input('slug');
        }
        if($request->work_exp){
            $row->work_exp = json_encode($request->work_exp);
        }else{
            $row->work_exp = '{}';
        }
        $res = $row->saveOriginOrTranslation($request->input('lang'),true);
        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            if($id > 0 ){
                return back()->with('success',  __('Job updated') );
            }else{
                return redirect(route('job.admin.edit',$row->id))->with('success', __('Job created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('job_manage_categories');
        if (empty($request->input('terms'))) {
            $this->JobTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->JobTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->JobTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }
    public function bulkEdit(Request $request)
    {
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action){
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->JobClass::where("id", $id);
                    if (!$this->hasPermission('job_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('job_delete');
                    }
                    $query->first();
                    if(!empty($query)){
                        $query->delete();
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->JobClass::where("id", $id);
                    if (!$this->hasPermission('job_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('job_delete');
                    }
                    $query->first();
                    if(!empty($query)){
                        $query->restore();
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('job_create');
                foreach ($ids as $id) {
                    (new $this->JobClass())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->JobClass::where("id", $id);
                    if (!$this->hasPermission('job_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('job_update');
                    }
                    $query->update(['status' => $action]);
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }
}
