<?php
namespace Modules\Job\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Models\Categories;
use Modules\Job\Models\JobRoom;
use Modules\Job\Models\JobRoomTerm;
use Modules\Job\Models\JobRoomTranslation;
use Modules\Location\Models\Location;
use Modules\Job\Models\Job;
use Modules\Job\Models\JobTerm;
use Modules\Job\Models\JobTranslation;
class RoomController extends AdminController
{
    protected $JobClass;
    protected $roomTermClass;
    protected $categoriesClass;
    protected $locationClass;
    /**
     * @var JobRoom
     */
    protected $roomClass;
    protected $currentJob;
    protected $roomTranslationClass;
    public function __construct()
    {
        parent::__construct();
        $this->setActiveMenu('admin/module/Job');
        $this->JobClass = Job::class;
        $this->roomTermClass = JobRoomTerm::class;
        $this->categoriesClass = Categories::class;
        $this->locationClass = Location::class;
        $this->roomClass = JobRoom::class;
        $this->roomTranslationClass = JobRoomTranslation::class;
    }
    public function callAction($method, $parameters)
    {
        if(!Job::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    protected function hasJobPermission($job_id = false){
        if(empty($job_id)) return false;
        $Job = $this->JobClass::find($job_id);
        if(empty($Job)) return false;
        if(!$this->hasPermission('job_manage_others') and $Job->create_user != Auth::id()){
            return false;
        }
        $this->currentJob = $Job;
        return true;
    }
    public function index(Request $request,$job_id)
    {
        $this->checkPermission('job_view');
        if(!$this->hasJobPermission($job_id))
        {
            abort(403);
        }
        $query = $this->roomClass::query() ;
        $query->orderBy('id', 'desc');
        if (!empty($job_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $job_name . '%');
            $query->orderBy('title', 'asc');
        }
        $query->where('parent_id',$job_id);
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'job_manage_others' => $this->hasPermission('job_manage_others'),
            'breadcrumbs'        => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/Job'
                ],
                [
                    'name' => __('Job: :name',['name'=>$this->currentJob->title]),
                    'url'  => 'admin/module/job/edit/'.$this->currentJob->id
                ],
                [
                    'name'  => __('Room Management'),
                    'class' => 'active'
                ],
            ],
            'page_title'=>__("Room Management"),
            'Job'=>$this->currentJob,
            'row'=> new $this->roomClass(),
            'translation'=>new $this->roomTranslationClass(),
            'categories'     => $this->categoriesClass::where('service', 'job_room')->get(),
        ];
        return view('Job::admin.room.index', $data);
    }
    public function edit(Request $request, $job_id,$id)
    {
        $this->checkPermission('job_update');
        if(!$this->hasJobPermission($job_id))
        {
            abort(403);
        }
        $row = $this->roomClass::find($id);
        if (empty($row) or $row->parent_id != $job_id) {
            return redirect(route('job.admin.room.index',['job_id'=>$job_id]));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        if (!$this->hasPermission('job_manage_others')) {
            if ($row->create_user != Auth::id()) {
                return redirect(route('job.admin.room.index'));
            }
        }
        $data = [
            'row'            => $row,
            'translation'    => $translation,
            "selected_terms" => $row->terms->pluck('term_id'),
            'categories'     => $this->categoriesClass::where('service', 'job_room')->get(),
            'enable_multi_lang'=>true,
            'breadcrumbs'    => [
                [
                    'name' => __('Jobs'),
                    'url'  => 'admin/module/Job'
                ],
                [
                    'name' => __('Job: :name',['name'=>$this->currentJob->title]),
                    'url'  => 'admin/module/job/edit/'.$this->currentJob->id
                ],
                [
                    'name' => __('All Rooms'),
                    'url'  => 'admin/module/job/room/'.$this->currentJob->id.'/index'
                ],
                [
                    'name' => __('Edit room: :name',['name'=>$row->title]),
                    'url'  => 'admin/module/job/room/'.$this->currentJob->id.'/edit/'.$id
                ],
            ],
            'page_title'=>__("Edit: :name",['name'=>$row->title]),
            'Job'=>$this->currentJob
        ];
        return view('Job::admin.room.detail', $data);
    }
    public function store( Request $request, $job_id,$id ){
        if(!$this->hasJobPermission($job_id))
        {
            abort(403);
        }
        if($id>0){
            $this->checkPermission('job_update');
            $row = $this->roomClass::find($id);
            if (empty($row)) {
                return redirect(route('job.admin.index'));
            }
            if($row->create_user != Auth::id() and !$this->hasPermission('job_manage_others'))
            {
                return redirect(route('job.admin.room.index'));
            }
            if($row->parent_id != $job_id)
            {
                return redirect(route('job.admin.room.index'));
            }
        }else{
            $this->checkPermission('job_create');
            $row = new $this->roomClass();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'image_id',
            'price',
            'number',
            'beds',
            'size',
            'adults',
            'children',
            'status',
        ];
        $row->fillByAttr($dataKeys,$request->input());
	    $row->ical_import_url  = $request->ical_import_url;
        if($id<0){
            $row->parent_id = $job_id;
        }
        $res = $row->saveOriginOrTranslation($request->input('lang'),true);
        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            if($id > 0 ){
                return redirect()->back()->with('success',  __('Room updated') );
            }else{
                return redirect()->back()->with('success',  __('Room created') );
            }
        }
    }
    public function saveTerms($row, $request)
    {
        $this->checkPermission('job_manage_categories');
        if (empty($request->input('terms'))) {
            $this->roomTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->roomTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->roomTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }
    public function bulkEdit(Request $request)
    {
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action){
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->roomClass::where("id", $id);
                    if (!$this->hasPermission('job_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('job_delete');
                    }
                    $query->first();
                    if(!empty($query)){
                        $query->delete();
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "clone":
                $this->checkPermission('job_create');
                foreach ($ids as $id) {
                    (new $this->roomClass())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->roomClass::where("id", $id);
                    if (!$this->hasPermission('job_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('job_update');
                    }
                    $query->update(['status' => $action]);
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }
}
